general:
  placeholder: '{placeholder}'
  format: '&'
  mentions:
    inFormat: '@{mentioned}'
    outFormat: '[{mentionedPrefix}]{mentioned}'
    outFormatMarker: '&6[{mentionedPrefix}]{mentioned}'

    message:
      # hotbar или chat
      display: 'hotbar'
      message: '&6Вас упомянули в чате!'
      selfReference: '&6Зачем упоминать себя?..'
    sound:
      # empty equals 'off'
      sound: 'BLOCK_BUBBLE_COLUMN_BUBBLE_POP'
      volume: '10'
      pitch: '1'
  chat:
    prefixError:
      display: 'chat'
      message: '{sender}, Ваше сообщение не было отправлено т.к. чат с соответствующим префиксом не был найден.'
    noOneHeard:
      display: 'hotbar'
      message: '{sender}, Вас никто не услышал... :('


#  #=#=#=#=#=#=#=#=#=#
#
#   prefix (префикс) - символ-якорь, по котрому определяется, в какой чат будет отправлено сообщение.
#   Чем ниже чат в списке, тем ниже его приоритет в определении префикса.
#   ### ВНИМАНИЕ!!! ### Префиксы не могут быть одинаковыми!
# <---------->
#   distance (дистанция) - радиус в блоках, в котром игроки получат сообщение. Положительное число. Иначе   ...
#   Eсли -1, то сообщение видно всем, кто находится в одном мире с отправителем.
#   Если -2, то сообщение видно всем игрокам в сети.
# <---------->
#   format (формат сообщение) - определяет то, как будет выглядеть сообщение в чате.
#   В нем могут присутствовать placeholder'ы, указанные в README файле на github.
# <---------->
#   color (цвет) - цвет и форматирование текста сообщения.
#   Нужено для того, что бы корректно отображать текст, идущий после упоминаний.
#   Оставьте пустым для установки стандартного форматирования (§r).
# <---------->
#   cooldown (таймер) - время в секундах, которое должно пройти, прежде чем
#                       игрок сможет вновь отправить сообщение в данный чат.
#   Оставьте пустым, либо установите "0" (без кавычек) для отключения
# <---------->
#   price (цена) - цена отправки сообщения.
#   ### ВНИМАНИЕ!!! ### Необходим Vault! Иначе игнорируется
# <---------->
#   mentions (упоминания) - разрешает или запрещает упоминать игроков в этом чате.
#   true - разрешает.
#   Любое другое - запрещает.
# <---------->
#   commands (команды) - команды, которые так же позволяют отправить сообщение в данный чат.
#   Перечисляйте их через запятую, либо оставьте пустым для отключения.
# <---------->
#   cmdUsage (использование) - сообщение, которое увидит игрок, если неверно передаст аргументы в команду.
#   Поддерживаются placeholder'ы, указанные в README файле на github.
#   Оставьте пустым для установки стандартного значения.
# <---------->
#   cmdDescription (описание) - описывает что делает(ют) эта(и) каманда(ы).
#   ЗАМЕТКА: рекомендую писать в единственном, а не множественном числе.
#   Оставьте пустым для установки стандартного значения.
# <---------->
#   log (логирование) - логирование чата в файл.
#   Введите формат в котором будут логироваться сообщения, либо оставьте пустым для отключения.
#   Поддерживаются placeholder'ы, указанные в README файле на github.
# <---------->
#   console (консоль) - отображение сообщений из чата в консоли.
#   Введите формат в котором будут отображаться сообщения, либо оставьте пустым для отключения.
#   Поддерживаются placeholder'ы, указанные в README файле на github.
# <---------->
#   noPerms (нет прав) - сообщение, которое увидит игрок, если у него недостаточно
#                        прав для отправки сообщения в данный чат.
#   Оставьте пустым для отключения.
# <---------->
#   notCooledDown (не остыл) - текст, который увидит игрок, если попытается
#                              отправить сообщение когда таймер еще не истёк.
#   Оставьте пустым для отключения.
# <---------->
#   noPermsMention (нет прав для упоминания) - сообщение, которое увидит игрок, если у него недостаточно
#                                              прав для упоминания других игрокво в данном чате.
#   Оставьте пустым для отключения.
#
#  ========================================================================================
#
#   prefixError (ошибка префикса) - сообщение, которое увидит игрок, если не был найден чат, в который можно
#                                   отправить данное сообщение (не был найден чат с соответствующим префиксом).
#   Оставьте false, либо пустым для отключения.
# <---------->
#   noOneHeard (никто не услышал) - сообщение, которое увидит игрок, если никто, кроме
#                                   кроме него самого не получил его сообщение.
#   Не работает, если игрок на сервере один.
#   Оставьте пустым для отключения.
#
#  #=#=#=#=#=#=#=#=#=#
chats:
  global:
    prefix: '!'
    distance: -2
    #sender
    format: '&f&6G&f | &2[{senderPrefix}]&6{sender} &6> {message}'
    color: '&f'
    cooldown: 0
    price: 0
    mentions: true
    commands: 'global'
    # без json, только цвета
    cmdUsage: 'Для отправки сообщения в чат используйте /{command} <message>, либо напишите "{chatPrefix}" перед сообщением.'
    # без json, только цвета
    cmdDescription: 'Отправка сообщения в глобальный чат.'
    log: false
    console: false
    noPerms: '&c{sender}, у Вас нет прав на отправку сообщений в Глобальный чат!'
    notCooledDown: '&cХей, {sender}! Полегче! Подожди еще {seconds}с, прежде чем отправить сообщение.'
    noPermsMention: '&c{sender}, у Вас нет прав на упоминание игроков в Глобальном чате!'
