globalChat:
  enable: 'true'
  prefix: '!'
  msgPrefix: '&f&6G&f | &6%sender%&f &6> '
  msgColor: '&9'
localChat:
  enable: 'true'
  prefix: ''
  msgPrefix: '&bL | &6%sender%&b > '
  msgColor: '&f'
  chatDistantion: '100'
  yDistantion: 'false'
worldChat:
  enable: 'true'
  prefix: '*'
  MsgPrefix: '&f&6W&f | &6%sender%&f &6> '
  MsgColor: '&f'
prefixError: 'Ваше сообщение не было отправлено т.к. чат с соответствующим префиксом ("%MessagePrefix%") не был найден. Доступные префиксы: %GlobalChatPrefix% - Глобальный чат, %LocalChatPrefix% - Локальный чат, %WorldChatPrefix% - Чат измерения.'
reload:
  success: '&aКонфиг был успешно перезагружен!'
  noPerms: '&cУ вас недостаточно прав для использования данной команды!'
