name: LightChat
version: '1.0'
main: tire.lightchat.main.LightChat
api-version: 1.18
softdepend: [ Vault, PlaceholderAPI ]
authors: [ TiRe_ ]
description: Chat plugin for minecraft
commands:
  lightchat:
    description: Plugin setup
    usage: /lightchat <reload>
    aliases: [ lightc, lchat, lc ]
