name: LightChat
version: '1.0-SNAPSHOT'
main: tire.lightchat.main.LightChat
api-version: 1.18
softdepend: [ Vault ]
authors: [ TiRe_ ]
description: Chat plugin for minecraft
commands:
  lightchat:
    description: Plugin setup
    usage: /lightchat
    aliases: [ lightc, lchat, lc ]
